// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Order.Frontend.Repositories;
using Orders.Shared.Entities;

namespace Order.Frontend.Components.Pages.Countries
{
    public partial class CountriesIndex
    {
        [Inject] private IRepository Repository { get; set; } = null!;
        private List<Country> Countries;

        protected override async Task OnInitializedAsync()
        {
            var httpResult = await Repository.GetAsync<List<Country>>("/api/countries");
            Countries = httpResult.Response;
        }
    }
}